from datetime import datetime, timedelta, timezone


def seed_payload() -> list[dict]:
    now = datetime.now(timezone.utc)
    return [
        {
            "title": "Bitcoin ETF flows rebound as traders rotate back into risk",
            "source": "CoinDesk",
            "author": "Desk Wire",
            "url": "https://www.coindesk.com/",
            "image_url": None,
            "published_at": now - timedelta(minutes=18),
            "category": "Crypto",
            "tags": ["bitcoin", "etf", "flows"],
            "excerpt": "Risk appetite returned across crypto majors after a quiet Asian session.",
            "short_summary": [
                "ETF inflows improved after recent outflows.",
                "Bitcoin led broad crypto risk-on positioning.",
                "Analysts see market structure stabilizing.",
            ],
            "overview": "ETF demand improved, Bitcoin outperformed peers, and traders positioned for a more stable risk backdrop.",
            "key_takeaways": [
                "Bitcoin demand is improving.",
                "Institutional flows remain central to sentiment.",
                "Market breadth expanded across majors.",
            ],
            "sentiment_score": 0.13,
            "sentiment_label": "bullish",
            "cluster_key": "bitcoin etf approval flows",
            "related_tickers": ["ETF", "USD"],
        },
        {
            "title": "Dollar firms ahead of Fed speakers while traders reprice cuts",
            "source": "ForexFactory",
            "author": "Macro Desk",
            "url": "https://www.forexfactory.com/news",
            "image_url": None,
            "published_at": now - timedelta(minutes=37),
            "category": "Forex",
            "tags": ["usd", "fed", "rates"],
            "excerpt": "FX markets stayed defensive before central bank commentary.",
            "short_summary": [
                "USD strengthened across majors.",
                "Rate-cut expectations were scaled back.",
                "Fed commentary remains the next catalyst.",
            ],
            "overview": "The dollar strengthened as the market dialed back aggressive easing bets before upcoming Federal Reserve remarks.",
            "key_takeaways": [
                "USD momentum remains firm.",
                "Fed communication is shaping near-term volatility.",
                "Rate expectations are driving FX repricing.",
            ],
            "sentiment_score": 0.01,
            "sentiment_label": "neutral",
            "cluster_key": "fed rate path usd",
            "related_tickers": ["USD", "FED"],
        },
        {
            "title": "Asian equities slip as oil rises on renewed geopolitical risk",
            "source": "Financial Times",
            "author": "Markets Desk",
            "url": "https://www.ft.com/markets",
            "image_url": None,
            "published_at": now - timedelta(hours=2),
            "category": "Geopolitics",
            "tags": ["oil", "asia", "risk"],
            "excerpt": "Equities softened while commodity-linked hedges attracted flows.",
            "short_summary": [
                "Equities weakened on renewed geopolitical concerns.",
                "Oil moved higher and pressured risk sentiment.",
                "Defensive positioning picked up across Asia.",
            ],
            "overview": "Renewed geopolitical tensions lifted oil and pushed Asian equities lower as investors rotated into defensive assets.",
            "key_takeaways": [
                "Oil is acting as a geopolitical risk gauge.",
                "Equity sentiment turned cautious.",
                "Cross-asset defensive flows increased.",
            ],
            "sentiment_score": -0.12,
            "sentiment_label": "bearish",
            "cluster_key": "geopolitical risk oil asia",
            "related_tickers": ["USD"],
        },
        {
            "title": "Sensex firms as foreign inflows steady while banks lead morning trade",
            "source": "Moneycontrol",
            "author": "Markets Bureau",
            "url": "https://www.moneycontrol.com/news/business/markets/sensex-firms-as-foreign-inflows-steady",
            "image_url": None,
            "published_at": now - timedelta(minutes=9),
            "category": "Stocks",
            "tags": ["sensex", "nifty", "india"],
            "excerpt": "Indian benchmarks stayed firm with banks and capital goods supporting the open.",
            "short_summary": ["Sensex opened firmer.", "Banking names led early gains.", "Foreign flow sentiment remained supportive."],
            "overview": "Indian equities stayed constructive in early trade as banks led gains and foreign flow expectations improved the tone.",
            "key_takeaways": ["India remained bid.", "Banks drove index strength.", "Market breadth improved in the first hour."],
            "sentiment_score": 0.14,
            "sentiment_label": "bullish",
            "cluster_key": "sensex nifty bank rally",
            "related_tickers": ["USD"],
        },
        {
            "title": "Government weighs fresh manufacturing incentives as capex theme regains traction",
            "source": "Economic Times Markets",
            "author": "ET Desk",
            "url": "https://economictimes.indiatimes.com/markets",
            "image_url": None,
            "published_at": now - timedelta(minutes=52),
            "category": "Macroeconomics",
            "tags": ["india", "policy", "manufacturing"],
            "excerpt": "Capital expenditure themes returned to focus as policy support discussions intensified.",
            "short_summary": ["Policy support is back in focus.", "Manufacturing-linked names are drawing attention.", "Capex remains a domestic market theme."],
            "overview": "Investors rotated toward manufacturing and infrastructure stories after renewed policy support chatter lifted capex-linked sentiment.",
            "key_takeaways": ["Policy headlines matter for domestic cyclicals.", "Capex remains a favored India theme.", "Infrastructure names may stay in focus."],
            "sentiment_score": 0.09,
            "sentiment_label": "bullish",
            "cluster_key": "india manufacturing capex policy",
            "related_tickers": [],
        },
        {
            "title": "Rupee steadies after early pressure as oil cools and exporters sell dollars",
            "source": "Moneycontrol",
            "author": "FX Desk",
            "url": "https://www.moneycontrol.com/news/business/markets/rupee-steadies-after-early-pressure",
            "image_url": None,
            "published_at": now - timedelta(minutes=6),
            "category": "Forex",
            "tags": ["rupee", "usd", "oil"],
            "excerpt": "The rupee stabilized as dollar supply improved and crude lost some momentum.",
            "short_summary": ["Rupee stabilized in afternoon trade.", "Oil cooled after an early spike.", "Exporter selling improved dollar supply."],
            "overview": "The rupee steadied as exporter dollar sales and softer crude eased some of the earlier pressure on the currency.",
            "key_takeaways": ["INR pressure eased.", "Oil remains a key driver.", "Dollar supply improved intraday."],
            "sentiment_score": 0.03,
            "sentiment_label": "neutral",
            "cluster_key": "rupee oil exporter dollars",
            "related_tickers": ["USD"],
        },
        {
            "title": "Yuan fix draws attention as traders watch Beijing support measures",
            "source": "Google News East Asia Markets",
            "author": "Asia Monitor",
            "url": "https://news.google.com/rss/search?q=yuan+fix+beijing+support+measures",
            "image_url": None,
            "published_at": now - timedelta(minutes=21),
            "category": "Macroeconomics",
            "tags": ["yuan", "china", "beijing"],
            "excerpt": "Regional desks tracked yuan stability and policy support expectations.",
            "short_summary": ["Yuan remains in focus.", "Beijing support hopes lifted sentiment.", "Asia desks watched the daily fix closely."],
            "overview": "Asian traders kept a close eye on the yuan as policy support speculation and the daily fix shaped regional sentiment.",
            "key_takeaways": ["USD/CNY is a regional signal.", "Policy hopes supported the mood.", "China remains central for Asia risk tone."],
            "sentiment_score": 0.02,
            "sentiment_label": "neutral",
            "cluster_key": "yuan beijing support fix",
            "related_tickers": ["USD"],
        },
        {
            "title": "Japan data calendar keeps yen traders cautious into the London handoff",
            "source": "Google News East Asia Markets",
            "author": "Asia FX",
            "url": "https://news.google.com/rss/search?q=japan+data+calendar+yen+london",
            "image_url": None,
            "published_at": now - timedelta(hours=1, minutes=12),
            "category": "Forex",
            "tags": ["yen", "boj", "japan"],
            "excerpt": "Japanese data and policy expectations kept FX desks cautious.",
            "short_summary": ["Yen trading stayed cautious.", "Data risk remained elevated.", "London handoff could bring broader direction."],
            "overview": "FX desks stayed cautious on the yen as Japanese data risk and policy expectations hovered over the London session handoff.",
            "key_takeaways": ["JPY remains event-sensitive.", "Session transition matters.", "BOJ pricing still shapes positioning."],
            "sentiment_score": -0.01,
            "sentiment_label": "neutral",
            "cluster_key": "yen data london handoff",
            "related_tickers": ["BOJ"],
        },
        {
            "title": "Defense procurement push lifts aerospace names after budget chatter",
            "source": "Google News Defense And Politics",
            "author": "Public Policy Desk",
            "url": "https://news.google.com/rss/search?q=defense+procurement+budget+india",
            "image_url": None,
            "published_at": now - timedelta(hours=3),
            "category": "Geopolitics",
            "tags": ["defense", "budget", "india"],
            "excerpt": "Defense and aerospace counters rose after fresh procurement headlines.",
            "short_summary": ["Defense names moved higher.", "Budget chatter supported procurement themes.", "Policy news drove sector rotation."],
            "overview": "Defense and aerospace shares gained after fresh procurement and budget headlines revived interest in government-linked spending themes.",
            "key_takeaways": ["Defense spending stories can move sectors quickly.", "Policy headlines fueled rotation.", "India-focused desks tracked procurement names."],
            "sentiment_score": 0.07,
            "sentiment_label": "bullish",
            "cluster_key": "defense budget procurement india",
            "related_tickers": [],
        },
        {
            "title": "Crude holds bid while Gulf tensions keep traders focused on supply risk",
            "source": "Financial Times",
            "author": "Energy Desk",
            "url": "https://www.ft.com/markets",
            "image_url": None,
            "published_at": now - timedelta(minutes=44),
            "category": "Commodities",
            "tags": ["crude", "oil", "gulf"],
            "excerpt": "Oil stayed supported as traders monitored geopolitical supply risk.",
            "short_summary": ["Crude held gains.", "Gulf tensions kept risk premium elevated.", "Energy remained a cross-asset driver."],
            "overview": "Crude prices stayed supported as geopolitical tensions preserved a risk premium and kept traders focused on supply disruption risk.",
            "key_takeaways": ["Oil remains a macro driver.", "Geopolitics still matters for pricing.", "Energy tone fed into broader risk sentiment."],
            "sentiment_score": -0.03,
            "sentiment_label": "neutral",
            "cluster_key": "crude gulf supply risk",
            "related_tickers": ["USD"],
        },
        {
            "title": "ETF chatter and stablecoin flows keep crypto desks active through Asia hours",
            "source": "CoinGecko",
            "author": "Crypto Pulse",
            "url": "https://www.coingecko.com/en/news",
            "image_url": None,
            "published_at": now - timedelta(minutes=12),
            "category": "Crypto",
            "tags": ["stablecoin", "etf", "crypto"],
            "excerpt": "Crypto traders tracked ETF developments and stablecoin liquidity conditions.",
            "short_summary": ["ETF headlines stayed in focus.", "Stablecoin flows supported activity.", "Asia crypto desks remained active."],
            "overview": "Crypto trading stayed active through Asia hours as ETF chatter and stablecoin liquidity kept traders engaged across major tokens.",
            "key_takeaways": ["ETF narratives remain important.", "Stablecoin flows signal liquidity.", "Asia session activity stayed solid."],
            "sentiment_score": 0.11,
            "sentiment_label": "bullish",
            "cluster_key": "etf stablecoin asia crypto",
            "related_tickers": ["ETF"],
        },
        {
            "title": "US futures steady as traders await housing data and central-bank remarks",
            "source": "Google News Global Markets",
            "author": "Global Wire",
            "url": "https://news.google.com/rss/search?q=us+futures+housing+data+fed",
            "image_url": None,
            "published_at": now - timedelta(minutes=28),
            "category": "Stocks",
            "tags": ["futures", "fed", "housing"],
            "excerpt": "US index futures steadied into key macro events.",
            "short_summary": ["US futures held steady.", "Housing data is the next catalyst.", "Central-bank remarks remain in focus."],
            "overview": "US futures traded steadily as markets waited for housing data and more central-bank commentary to sharpen the macro outlook.",
            "key_takeaways": ["Macro events still drive equities.", "Futures were stable before data.", "Fed tone remains a headline catalyst."],
            "sentiment_score": 0.01,
            "sentiment_label": "neutral",
            "cluster_key": "us futures housing fed",
            "related_tickers": ["FED", "USD"],
        },
        {
            "title": "Weekly digest: India, crypto ETFs and crude lead cross-asset attention",
            "source": "Market Pulse Atom",
            "author": "Desk Summary",
            "url": "https://news.google.com/rss/search?q=weekly+digest+india+crypto+crude",
            "image_url": None,
            "published_at": now - timedelta(days=3),
            "category": "Macroeconomics",
            "tags": ["weekly", "india", "crypto", "crude"],
            "excerpt": "The week centered on Indian equities, ETF demand and oil risk premium.",
            "short_summary": ["India stayed resilient.", "Crypto ETF narratives stayed strong.", "Oil risk remained a headline theme."],
            "overview": "Across the week, Indian equities, crypto ETF demand and oil-related geopolitical risk shaped the market conversation.",
            "key_takeaways": ["India remained a domestic bright spot.", "ETF demand drove crypto tone.", "Oil kept the macro backdrop sensitive."],
            "sentiment_score": 0.06,
            "sentiment_label": "bullish",
            "cluster_key": "weekly india etf crude",
            "related_tickers": ["ETF", "USD"],
        },
    ]
